from enum import Enum

class Action(str, Enum):
    VIEW_INVENTORY = "VIEW_INVENTORY"
    VIEW_RISK = "VIEW_RISK"
    VIEW_DECISION = "VIEW_DECISION"
    VIEW_HISTORY = "VIEW_HISTORY"
    VIEW_OUTCOME = "VIEW_OUTCOME"
    ANALYZE_WORKFLOW = "ANALYZE_WORKFLOW"
    VIEW_TRANSFER = "VIEW_TRANSFER"
    
    CREATE_TRANSFER = "CREATE_TRANSFER"
    APPROVE_TRANSFER = "APPROVE_TRANSFER"
    ASSIGN_TRANSFER = "ASSIGN_TRANSFER"
    START_TRANSFER = "START_TRANSFER"
    COMPLETE_TRANSFER = "COMPLETE_TRANSFER"
    CANCEL_TRANSFER = "CANCEL_TRANSFER"
    
    MODIFY_FINALIZED_OUTCOME = "MODIFY_FINALIZED_OUTCOME"
